CREATE TABLE IF NOT EXISTS schedules (
  id CHAR(36) NOT NULL,
  date CHAR(10) NULL,
  start_time CHAR(5) NOT NULL,
  max_number INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);