// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mizuki-n-2/reservation_sample_api/controller"
	"github.com/mizuki-n-2/reservation_sample_api/infra"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitDI(db *gorm.DB) *DIContainer {
	adminRepository := infra.NewAdminRepository(db)
	adminController := controller.NewAdminController(adminRepository)
	scheduleRepository := infra.NewScheduleRepository(db)
	scheduleController := controller.NewScheduleController(scheduleRepository, adminRepository)
	reservationRepository := infra.NewReservationRepository(db)
	reservationController := controller.NewReservationController(reservationRepository, scheduleRepository)
	diContainer := &DIContainer{
		AdminController:       adminController,
		ScheduleController:    scheduleController,
		ReservationController: reservationController,
	}
	return diContainer
}

// wire.go:

type DIContainer struct {
	AdminController       controller.AdminController
	ScheduleController    controller.ScheduleController
	ReservationController controller.ReservationController
}
