// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/mizuki-n-2/reservation_sample_api/controller"
	"github.com/mizuki-n-2/reservation_sample_api/infra"
	"github.com/mizuki-n-2/reservation_sample_api/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitDI(db *gorm.DB) *Controllers {
	adminRepository := infra.NewAdminRepository(db)
	authService := service.NewAuthService(adminRepository)
	adminController := controller.NewAdminController(authService, adminRepository)
	scheduleRepository := infra.NewScheduleRepository(db)
	scheduleController := controller.NewScheduleController(scheduleRepository, adminRepository)
	reservationRepository := infra.NewReservationRepository(db)
	reservationController := controller.NewReservationController(reservationRepository, scheduleRepository)
	controllers := &Controllers{
		AdminController:       adminController,
		ScheduleController:    scheduleController,
		ReservationController: reservationController,
	}
	return controllers
}

// wire.go:

type Controllers struct {
	AdminController       controller.AdminController
	ScheduleController    controller.ScheduleController
	ReservationController controller.ReservationController
}
